AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Assemble Lambda Function Backend
Resources:
  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create-user/
      Handler: index.handler
      Runtime: nodejs10.x
      Events:
        CreateUser:
          Type: Api
          Properties:
            Path: /CreateUser
            Method: post
  AuthenticateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: authenticate-user/
      Handler: index.handler
      Runtime: nodejs10.x
      Events:
        AuthenticateUser:
          Type: Api
          Properties:
            Path: /AuthenticateUser
            Method: post
Outputs:
  CreateUserApi:
    Description: API Gateway CreateUser for Assemble
    Value: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
  CreateUserFunction:
    Description: CreateUser Lambda Function ARN
    Value: CreateUserFunction.Arn
  CreateUserRequestIamRole:
    Description: Implicit IAM Role created for CreateUser Request function
    Value: CreateUserFunctionRole.Arn
  AuthenticateUserApi:
    Description: API Gateway AuthenticateUser for Assemble
    Value: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
  AuthenticateUserFunction:
    Description: AuthenticateUser Lambda Function ARN
    Value: AuthenticateUserFunction.Arn
  AuthenticateUserRequestIamRole:
    Description: Implicit IAM Role created for AuthenticateUser Request function
    Value: AuthenticateUserFunctionRole.Arn
