AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CreateUser
  
Globals:
  Function:
    Timeout: 3

Resources:
  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create-user/
      Handler: index.handler
      Runtime: nodejs10.x
      Events:
        UserInfo:
          Type: Api
          Properties:
            Path: /CreateUser
            Method: post

Outputs:
  CreateUserApi:
    Description: "API Gateway create user for Assemble"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  HandleUserRequestFunction:
    Description: "Create User Lambda Function ARN"
    Value: !GetAtt CreateUserFunction.Arn
  HandleUserRequestIamRole:
    Description: "Implicit IAM Role created for Create User Request function"
    Value: !GetAtt CreateUserFunctionRole.Arn
