AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Assemble Lambda Function Backend
Resources:
  AuthenticateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: authenticate-user/
      Handler: index.handler
      Runtime: nodejs10.x
      Events:
        AuthenticateUser:
          Type: Api
          Properties:
            Path: /AuthenticateUser
            Method: post
Outputs:
  AuthenticateUserApi:
    Description: API Gateway AuthenticateUser for Assemble
    Value: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
  AuthenticateUserFunction:
    Description: AuthenticateUser Lambda Function ARN
    Value: AuthenticateUserFunction.Arn
  AuthenticateUserRequestIamRole:
    Description: Implicit IAM Role created for AuthenticateUser Request function
    Value: AuthenticateUserFunctionRole.Arn
